BYTE-158: Styling Zaius Countdown Timer
astrogoat/zaius pull request #6
Opened 2023-07-21 11:08 UTC by iamkarsoft

**Link to ticket**: https://linear.app/3zbrands/issue/BYTE-158/styling

<details>
<summary>Ticket description</summary>
As a user looking at the promobar when the countdown timer is enabled, I want to see the countdown timer sitting between the copy and the View Offer link (if it exists) so that I know how much time remains until the sale ends.
</details>

2023-07-21 12:11 UTC, BaffourAdu approved these changes

2023-07-24 12:28 UTC, tonning requested changes

2023-07-24 12:28 UTC, tonning commented on resources/views/promobar/components/countdown.blade.php
Hi Kofi, unfortunately we can't rely on Tailwind classes always being available to us here, only if the site the Zaius promobar is used on also has generated that class because it needs it somewhere else will it be available. So we need to explicitly define them to be on the safe site.
The easiest way is likely to copy the CSS that Tailwind generates for each of the used classes and add as inline styles.

2023-07-24 12:43 UTC, iamkarsoft commented on resources/views/promobar/components/countdown.blade.php
will work on that! Thanks

2023-07-26 14:44 UTC, nrthbound commented on resources/views/promobar/components/countdown.blade.php
> +                    secondsBlockTwo.textContent = String(this.timer.seconds % 10);
Wow. All of this time math hurts my brain, but well done. You're a better man than me, because I definitely would have reached for `date-fns` haha.

2023-07-27 09:26 UTC, tonning approved these changes

2023-07-27 09:27 UTC, merged